### PR TITLE
git-secret added

### PR DESCRIPTION
**Pull request by sobolevn**
Here's a link to the added package: https://github.com/sobolevn/git-secret

### CODE REVIEW

**Comment by stevemao** [comment]
@sobolevn Thanks for the PR. I feel the gif is too slow. Would be great if you provide a text version. Thanks.

**Comment by sobolevn** [comment]
Yes, it's a bit slow. I will make it faster soon.

**Comment by stevemao** [comment]
I prefer to use text version in this repo (and it's easier for you to copy and paste here) because there is no animation going on.

**Comment by sobolevn** [comment]
ok, will do.

**Pull request merged**
